[package]
name = "jasshaus-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
yew = { version = "0.20" }
quote = "1.0.33"
proc-macro2 = "1.0.67"

jasshaus-traits = { path = "../traits/" }

[dependencies.syn]
version = "2.0"
features = [
 "derive",
]
