[package]
name = "jasshaus-traits"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
yew = { version = "0.20" }
wasm-bindgen = "0.2.87"

[dependencies.web-sys]
version = "0.3.64"
features = [
 "HtmlInputElement",
 "EventTarget",
 "FocusEvent",
]